import { 
  Activity, 
  Brain, 
  Siren, 
  ShieldAlert, 
  Phone, 
  MapPin, 
  User, 
  Wifi, 
  WifiOff, 
  Zap, 
  Mic, 
  MicOff,
  Camera, 
  CameraOff,
  ChevronLeft,
  Send,
  MoreVertical,
  Menu,
  Stethoscope,
  BookOpen,
  Check,
  X,
  Volume2,
  StopCircle,
  Scan,
  Maximize2,
  HeartPulse,
  Clock,
  Droplet,
  UserX,
  Play,
  BarChart2,
  GraduationCap,
  Trophy,
  Target,
  AlertTriangle,
  RotateCcw,
  PhoneCall,
  Share2,
  Radio,
  FileText,
  Users,
  Navigation,
  Lock,
  MessageSquare,
  Video,
  Search
} from 'lucide-react';

export const Icons = {
  Interactive: Activity,
  Learning: BookOpen,
  Analysis: Stethoscope,
  Bridge: Phone,
  Emergency: Siren,
  Profile: User,
  Location: MapPin,
  Wifi: Wifi,
  WifiOff: WifiOff,
  AI: Brain,
  Energy: Zap,
  Mic: Mic,
  MicOff: MicOff,
  Camera: Camera,
  CameraOff: CameraOff,
  Back: ChevronLeft,
  Send: Send,
  Options: MoreVertical,
  Menu: Menu,
  Warning: ShieldAlert,
  Check: Check,
  Close: X,
  Volume: Volume2,
  Stop: StopCircle,
  Scan: Scan,
  Maximize: Maximize2,
  CPR: HeartPulse,
  Timer: Clock,
  Bleeding: Droplet,
  Unconscious: UserX,
  Play: Play,
  Chart: BarChart2,
  Education: GraduationCap,
  Trophy: Trophy,
  Target: Target,
  Alert: AlertTriangle,
  Retry: RotateCcw,
  PhoneCall: PhoneCall,
  Share: Share2,
  Radio: Radio,
  Report: FileText,
  Contacts: Users,
  Navigation: Navigation,
  Lock: Lock,
  Message: MessageSquare,
  Video: Video,
  Search: Search
};